# Generated by Django 4.0.1 on 2022-01-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meong2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='waifu',
            name='faction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bolo', to='meong2.faction'),
        ),
    ]
